spring.application.name=Hiccupify

spring.datasource.url=jdbc:postgresql://localhost:5432/Hiccupify

# Database credentials
spring.datasource.username=postgres
spring.datasource.password=root

# JDBC driver class
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate dialect for PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Optional: automatically create/update tables (use carefully)
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in console (optional, useful for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.auto_index_ddl=true


#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql

api.prefix=/api/v1
